"""gruppe b regeln vergleiche

Revision ID: 0002
Revises: 0001
Create Date: 2026-10-01 13:56:55.105973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0002'
down_revision: Union[str, Sequence[str], None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('match_decisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('manufacturer_id', sa.Integer(), nullable=True),
    sa.Column('old_number_normalized', sa.String(length=100), nullable=False),
    sa.Column('new_number_normalized', sa.String(length=100), nullable=False),
    sa.Column('decision', sa.String(length=10), nullable=False),
    sa.Column('decided_by', sa.Integer(), nullable=False),
    sa.Column('decided_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['decided_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['manufacturer_id'], ['manufacturers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('manufacturer_id', 'old_number_normalized', 'new_number_normalized')
    )
    op.create_table('rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('manufacturer_id', sa.Integer(), nullable=True),
    sa.Column('current_version', sa.Integer(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['manufacturer_id'], ['manufacturers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rule_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('definition', sa.JSON(), nullable=False),
    sa.Column('comment', sa.String(length=500), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['rule_id'], ['rules.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rule_id', 'version')
    )
    op.create_table('calculation_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('price_list_id', sa.Integer(), nullable=False),
    sa.Column('rule_version_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.String(length=40), nullable=False),
    sa.Column('summary', sa.JSON(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['price_list_id'], ['price_lists.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rule_version_id'], ['rule_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comparisons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('old_price_list_id', sa.Integer(), nullable=False),
    sa.Column('new_price_list_id', sa.Integer(), nullable=False),
    sa.Column('manufacturer_id', sa.Integer(), nullable=True),
    sa.Column('price_type', sa.String(length=10), nullable=False),
    sa.Column('rule_version_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.String(length=40), nullable=False),
    sa.Column('summary', sa.JSON(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['manufacturer_id'], ['manufacturers.id'], ),
    sa.ForeignKeyConstraint(['new_price_list_id'], ['price_lists.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['old_price_list_id'], ['price_lists.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rule_version_id'], ['rule_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('calculation_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('start_amount', sa.String(length=40), nullable=True),
    sa.Column('result_amount', sa.String(length=40), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('trace', sa.JSON(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['calculation_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('calculation_results', schema=None) as batch_op:
        batch_op.create_index('ix_calc_results_run', ['run_id', 'status'], unique=False)

    op.create_table('comparison_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comparison_id', sa.Integer(), nullable=False),
    sa.Column('old_article_id', sa.Integer(), nullable=True),
    sa.Column('new_article_id', sa.Integer(), nullable=True),
    sa.Column('manufacturer_id', sa.Integer(), nullable=True),
    sa.Column('article_number', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=200), nullable=True),
    sa.Column('min_quantity', sa.String(length=40), nullable=True),
    sa.Column('status', sa.String(length=25), nullable=False),
    sa.Column('old_amount', sa.String(length=40), nullable=True),
    sa.Column('new_amount', sa.String(length=40), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('difference', sa.String(length=40), nullable=True),
    sa.Column('difference_percent', sa.String(length=40), nullable=True),
    sa.Column('match_method', sa.String(length=20), nullable=True),
    sa.Column('confidence', sa.String(length=40), nullable=True),
    sa.Column('changed_fields', sa.JSON(), nullable=True),
    sa.Column('candidates', sa.JSON(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['comparison_id'], ['comparisons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['manufacturer_id'], ['manufacturers.id'], ),
    sa.ForeignKeyConstraint(['new_article_id'], ['articles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['old_article_id'], ['articles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('comparison_items', schema=None) as batch_op:
        batch_op.create_index('ix_comparison_items_new', ['comparison_id', 'new_article_id'], unique=False)
        batch_op.create_index('ix_comparison_items_status', ['comparison_id', 'status'], unique=False)

    with op.batch_alter_table('manufacturers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ignore_leading_zeros', sa.Boolean(), server_default='1', nullable=False))

    # ### end Alembic commands ###
    # Regelversionen sind nach dem Speichern unveränderlich
    op.execute("""CREATE TRIGGER rule_versions_no_update BEFORE UPDATE ON rule_versions
        BEGIN SELECT RAISE(ABORT, 'Regelversionen sind unveraenderlich'); END""")
    op.execute("""CREATE TRIGGER rule_versions_no_delete BEFORE DELETE ON rule_versions
        BEGIN SELECT RAISE(ABORT, 'Regelversionen sind unveraenderlich'); END""")


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP TRIGGER IF EXISTS rule_versions_no_update")
    op.execute("DROP TRIGGER IF EXISTS rule_versions_no_delete")
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('manufacturers', schema=None) as batch_op:
        batch_op.drop_column('ignore_leading_zeros')

    with op.batch_alter_table('comparison_items', schema=None) as batch_op:
        batch_op.drop_index('ix_comparison_items_status')
        batch_op.drop_index('ix_comparison_items_new')

    op.drop_table('comparison_items')
    with op.batch_alter_table('calculation_results', schema=None) as batch_op:
        batch_op.drop_index('ix_calc_results_run')

    op.drop_table('calculation_results')
    op.drop_table('comparisons')
    op.drop_table('calculation_runs')
    op.drop_table('rule_versions')
    op.drop_table('rules')
    op.drop_table('match_decisions')
    # ### end Alembic commands ###
