"""hersteller kuerzel

Revision ID: 0004
Revises: 0003
Create Date: 2026-10-02 08:46:49.858248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0004'
down_revision: Union[str, Sequence[str], None] = '0003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('manufacturers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('code', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('default_rule_id', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint('uq_manufacturers_code', ['code'])
        batch_op.create_foreign_key('fk_manufacturers_default_rule', 'rules', ['default_rule_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('manufacturers', schema=None) as batch_op:
        batch_op.drop_constraint('fk_manufacturers_default_rule', type_='foreignkey')
        batch_op.drop_constraint('uq_manufacturers_code', type_='unique')
        batch_op.drop_column('default_rule_id')
        batch_op.drop_column('code')

    # ### end Alembic commands ###
