"""preisaktualisierung

Revision ID: 0005
Revises: 0004
Create Date: 2026-10-02 10:45:01.298523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0005'
down_revision: Union[str, Sequence[str], None] = '0004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('price_updates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('base_price_list_id', sa.Integer(), nullable=False),
    sa.Column('source_price_list_id', sa.Integer(), nullable=False),
    sa.Column('price_type', sa.String(length=10), nullable=False),
    sa.Column('rule_version_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.String(length=40), nullable=False),
    sa.Column('summary', sa.JSON(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['base_price_list_id'], ['price_lists.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['rule_version_id'], ['rule_versions.id'], ),
    sa.ForeignKeyConstraint(['source_price_list_id'], ['price_lists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('price_update_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('update_id', sa.Integer(), nullable=False),
    sa.Column('base_article_id', sa.Integer(), nullable=False),
    sa.Column('source_article_id', sa.Integer(), nullable=True),
    sa.Column('manufacturer_id', sa.Integer(), nullable=True),
    sa.Column('article_number', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('old_amount', sa.String(length=40), nullable=True),
    sa.Column('new_amount', sa.String(length=40), nullable=True),
    sa.Column('calculated_amount', sa.String(length=40), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('difference', sa.String(length=40), nullable=True),
    sa.Column('difference_percent', sa.String(length=40), nullable=True),
    sa.Column('match_method', sa.String(length=20), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('trace', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['base_article_id'], ['articles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['manufacturer_id'], ['manufacturers.id'], ),
    sa.ForeignKeyConstraint(['source_article_id'], ['articles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['update_id'], ['price_updates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('price_update_items', schema=None) as batch_op:
        batch_op.create_index('ix_price_update_items_status', ['update_id', 'status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('price_update_items', schema=None) as batch_op:
        batch_op.drop_index('ix_price_update_items_status')

    op.drop_table('price_update_items')
    op.drop_table('price_updates')
    # ### end Alembic commands ###
