"""jahresabgleich

Revision ID: 0006
Revises: 0005
Create Date: 2026-10-02 11:10:35.646723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0006'
down_revision: Union[str, Sequence[str], None] = '0005'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('manufacturers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('list_basis', sa.String(length=5), server_default='EK', nullable=False))
        batch_op.add_column(sa.Column('dealer_discount', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('review_threshold', sa.String(length=40), server_default='10', nullable=False))

    with op.batch_alter_table('price_lists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kind', sa.String(length=12), nullable=True))

    with op.batch_alter_table('price_update_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_amount', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('vk_old', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('vk_difference', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('vk_difference_percent', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('final_ek', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('final_vk', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('decision', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('reasons', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('candidates', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('needs_review', sa.Boolean(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('reviewed_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('reviewed_at', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key('fk_price_update_items_reviewed_by', 'users', ['reviewed_by'], ['id'])

    with op.batch_alter_table('price_updates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dealer_discount', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('review_threshold', sa.String(length=40), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('price_updates', schema=None) as batch_op:
        batch_op.drop_column('review_threshold')
        batch_op.drop_column('dealer_discount')

    with op.batch_alter_table('price_update_items', schema=None) as batch_op:
        # WARNING: constraint name is None; this directive will fail as
        # rendered.  Add a name, or use a naming convention; see
        # https://alembic.sqlalchemy.org/en/latest/naming.html
        batch_op.drop_constraint('fk_price_update_items_reviewed_by', type_='foreignkey')
        batch_op.drop_column('reviewed_at')
        batch_op.drop_column('reviewed_by')
        batch_op.drop_column('needs_review')
        batch_op.drop_column('candidates')
        batch_op.drop_column('reasons')
        batch_op.drop_column('decision')
        batch_op.drop_column('final_vk')
        batch_op.drop_column('final_ek')
        batch_op.drop_column('vk_difference_percent')
        batch_op.drop_column('vk_difference')
        batch_op.drop_column('vk_old')
        batch_op.drop_column('source_amount')

    with op.batch_alter_table('price_lists', schema=None) as batch_op:
        batch_op.drop_column('kind')

    with op.batch_alter_table('manufacturers', schema=None) as batch_op:
        batch_op.drop_column('review_threshold')
        batch_op.drop_column('dealer_discount')
        batch_op.drop_column('list_basis')

    # ### end Alembic commands ###
