"""Währungsumrechnung, Serien-Ausnahmen, Teillisten, Übernahme als aktuelle Liste

Revision ID: 0007
Revises: 0006
Create Date: 2026-10-04 16:10:18.133655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0007'
down_revision: Union[str, Sequence[str], None] = '0006'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rule_exceptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('manufacturer_id', sa.Integer(), nullable=False),
    sa.Column('match_type', sa.String(length=10), nullable=False),
    sa.Column('value', sa.String(length=200), nullable=False),
    sa.Column('value_normalized', sa.String(length=200), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('note', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['manufacturer_id'], ['manufacturers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rule_id'], ['rules.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('manufacturer_id', 'match_type', 'value_normalized', name='uq_rule_exceptions_match')
    )
    with op.batch_alter_table('rule_exceptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rule_exceptions_manufacturer_id'), ['manufacturer_id'], unique=False)

    with op.batch_alter_table('manufacturers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('list_currency', sa.String(length=3), server_default='EUR', nullable=False))
        batch_op.add_column(sa.Column('exchange_rate', sa.String(length=40), nullable=True))

    with op.batch_alter_table('price_update_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_currency', sa.String(length=3), nullable=True))
        batch_op.add_column(sa.Column('ek_text', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('rule_label', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('factor', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('check_ok', sa.Boolean(), nullable=True))

    with op.batch_alter_table('price_updates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scope', sa.String(length=5), server_default='VOLL', nullable=False))
        batch_op.add_column(sa.Column('list_currency', sa.String(length=3), nullable=True))
        batch_op.add_column(sa.Column('exchange_rate', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('exceptions', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('adopted_list_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_price_updates_adopted_list', 'price_lists', ['adopted_list_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('price_updates', schema=None) as batch_op:
        batch_op.drop_constraint('fk_price_updates_adopted_list', type_='foreignkey')
        batch_op.drop_column('adopted_list_id')
        batch_op.drop_column('exceptions')
        batch_op.drop_column('exchange_rate')
        batch_op.drop_column('list_currency')
        batch_op.drop_column('scope')

    with op.batch_alter_table('price_update_items', schema=None) as batch_op:
        batch_op.drop_column('check_ok')
        batch_op.drop_column('factor')
        batch_op.drop_column('rule_label')
        batch_op.drop_column('ek_text')
        batch_op.drop_column('source_currency')

    with op.batch_alter_table('manufacturers', schema=None) as batch_op:
        batch_op.drop_column('exchange_rate')
        batch_op.drop_column('list_currency')

    with op.batch_alter_table('rule_exceptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rule_exceptions_manufacturer_id'))

    op.drop_table('rule_exceptions')
    # ### end Alembic commands ###
