"""KI-Einschätzung zu fehlenden/unklaren Artikeln im Jahresabgleich

Revision ID: 0008
Revises: 0007
Create Date: 2026-10-04 17:24:30.605477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0008'
down_revision: Union[str, Sequence[str], None] = '0007'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('price_update_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai_hint', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('price_update_items', schema=None) as batch_op:
        batch_op.drop_column('ai_hint')

    # ### end Alembic commands ###
