"""Eigentümer: jeder Benutzer hat eigene Hersteller und Regeln (Name/Kürzel pro Besitzer eindeutig)

Revision ID: 0009
Revises: 0008
Create Date: 2026-10-05 06:25:06.778644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0009'
down_revision: Union[str, Sequence[str], None] = '0008'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


NAMING = {"uq": "uq_%(table_name)s_%(column_0_name)s"}


def upgrade() -> None:
    """Upgrade schema."""
    # naming_convention gibt dem unbenannten UNIQUE(name) aus 0001 einen Namen, damit er entfernt werden kann
    with op.batch_alter_table('manufacturers', schema=None, naming_convention=NAMING) as batch_op:
        batch_op.add_column(sa.Column('owner_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('uq_manufacturers_name', type_='unique')
        batch_op.drop_constraint('uq_manufacturers_code', type_='unique')
        batch_op.create_index(batch_op.f('ix_manufacturers_owner_id'), ['owner_id'], unique=False)
        batch_op.create_unique_constraint('uq_manufacturers_owner_code', ['owner_id', 'code'])
        batch_op.create_unique_constraint('uq_manufacturers_owner_name', ['owner_id', 'name'])
        batch_op.create_foreign_key('fk_manufacturers_owner', 'users', ['owner_id'], ['id'])

    with op.batch_alter_table('rules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_rules_owner_id'), ['owner_id'], unique=False)
        batch_op.create_foreign_key('fk_rules_owner', 'users', ['owner_id'], ['id'])

    # Bestand gehört dem ersten Administrator
    admin = "(SELECT MIN(id) FROM users WHERE role = 'admin')"
    op.execute(f"UPDATE manufacturers SET owner_id = {admin} WHERE owner_id IS NULL")
    op.execute(f"UPDATE rules SET owner_id = {admin} WHERE owner_id IS NULL")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rules', schema=None) as batch_op:
        batch_op.drop_constraint('fk_rules_owner', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_rules_owner_id'))
        batch_op.drop_column('owner_id')

    with op.batch_alter_table('manufacturers', schema=None) as batch_op:
        batch_op.drop_constraint('fk_manufacturers_owner', type_='foreignkey')
        batch_op.drop_constraint('uq_manufacturers_owner_name', type_='unique')
        batch_op.drop_constraint('uq_manufacturers_owner_code', type_='unique')
        batch_op.drop_index(batch_op.f('ix_manufacturers_owner_id'))
        batch_op.create_unique_constraint('uq_manufacturers_code', ['code'])
        batch_op.create_unique_constraint('uq_manufacturers_name', ['name'])
        batch_op.drop_column('owner_id')

    # ### end Alembic commands ###
