"""Jahresabgleich: neue Preise gültig ab

Revision ID: 0010
Revises: 0009
Create Date: 2026-10-06 08:51:48.708662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0010'
down_revision: Union[str, Sequence[str], None] = '0009'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('price_updates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('valid_from', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('price_updates', schema=None) as batch_op:
        batch_op.drop_column('valid_from')

    # ### end Alembic commands ###
